apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
        name: kedademoapi-scaler
spec:
  scaleTargetRef:
    name: simple-web
  minReplicaCount: 1
  maxReplicaCount: 10
  cooldownPeriod: 30
  triggers:
  - type: memory
    metadata:
      type: Utilization
      value: "70"
  - type: cpu
    metadata:
      type: Utilization
      value: "50"
